components:
  schemas:
    Program:
      type: object
      properties:
        name:
          type: string
          description: Name of the program
          example: 'ctf-program-01'
        assets:
          type: array
          description: Assets of the program
        challenges:
          type: array
          description: Challenges of the program
      required:
        - name
        - assets
        - challenges
        